/**
 * Autocompletion
 * Description de l'API du service d'autocompletion de l'IGN
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetcapabilitiesParameters } from './getcapabilitiesParameters';

export interface GetcapabilitiesOperations { 
    id?: string;
    description?: string;
    url?: string;
    methods?: Array<GetcapabilitiesOperations.MethodsEnum>;
    parameters?: Array<GetcapabilitiesParameters>;
}
export namespace GetcapabilitiesOperations {
    export type MethodsEnum = 'GET' | 'POST' | 'PUT' | 'DELETE';
    export const MethodsEnum = {
        GET: 'GET' as MethodsEnum,
        POST: 'POST' as MethodsEnum,
        PUT: 'PUT' as MethodsEnum,
        DELETE: 'DELETE' as MethodsEnum
    };
}