/**
 * Autocompletion
 * Description de l'API du service d'autocompletion de l'IGN
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetcapabilitiesFields } from './getcapabilitiesFields';

export interface GetcapabilitiesIndexes { 
    id?: string;
    description?: string;
    fields?: Array<GetcapabilitiesFields>;
}