/**
 * Autocompletion
 * Description de l'API du service d'autocompletion de l'IGN
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetcapabilitiesApi } from './getcapabilitiesApi';
import { GetcapabilitiesIndexes } from './getcapabilitiesIndexes';
import { GetcapabilitiesInfo } from './getcapabilitiesInfo';
import { GetcapabilitiesOperations } from './getcapabilitiesOperations';

export interface Getcapabilities { 
    info?: GetcapabilitiesInfo;
    api?: GetcapabilitiesApi;
    operations?: Array<GetcapabilitiesOperations>;
    indexes?: Array<GetcapabilitiesIndexes>;
}