/**
 * Autocompletion
 * Description de l'API du service d'autocompletion de l'IGN
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetcapabilitiesSchema } from './getcapabilitiesSchema';

export interface GetcapabilitiesParameters { 
    name?: string;
    _in?: string;
    description?: string;
    required?: boolean;
    /**
     * default value
     */
    _default?: any;
    schema?: GetcapabilitiesSchema;
    example?: string;
}